name: Deploy Docs
on:
  push:
    branches: [main]
    tags: ["v*"]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-deploy-docs
  cancel-in-progress: false
jobs:
  deploy-docs-next:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}-docs:next
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          cache-from: type=gha,scope=docs-app
          cache-to: type=gha,mode=max,scope=docs-app
          tags: ${{ env.DOCKER_IMAGE }}
          file: ./docs.Dockerfile
  run-docs-next:
    needs: deploy-docs-next
    runs-on: ubuntu-latest
    env:
      NAME: ui-react-docs-next
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}-docs:next
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.KIBA_APP_BOX_URL }}
          username: ${{ secrets.KIBA_APP_BOX_USER }}
          key: ${{ secrets.KIBA_APP_BOX_SSH_KEY }}
          port: ${{ secrets.KIBA_APP_BOX_PORT }}
          envs: DOCKER_IMAGE,NAME
          script_stop: true
          script: |
            url="ui-react-docs-next.kibalabs.com"
            varsFile=~/.${NAME}.vars
            docker pull ${DOCKER_IMAGE}
            docker stop ${NAME} && docker rm ${NAME} || true
            docker run \
                --name ${NAME} \
                --detach \
                --publish-all \
                --restart on-failure \
                --env NAME=${NAME} \
                --env VIRTUAL_HOST=${url} \
                --env LETSENCRYPT_HOST=${url} \
                --env-file ${varsFile} \
                ${DOCKER_IMAGE}
  deploy-docs:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}-docs:latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          cache-from: type=gha,scope=docs-app
          cache-to: type=gha,mode=max,scope=docs-app
          tags: ${{ env.DOCKER_IMAGE }}
          file: ./docs.Dockerfile
  run-docs:
    needs: deploy-docs
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    env:
      NAME: ui-react-docs
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}-docs:latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.KIBA_APP_BOX_URL }}
          username: ${{ secrets.KIBA_APP_BOX_USER }}
          key: ${{ secrets.KIBA_APP_BOX_SSH_KEY }}
          port: ${{ secrets.KIBA_APP_BOX_PORT }}
          envs: DOCKER_IMAGE,NAME
          script_stop: true
          script: |
            url="ui-react-docs.kibalabs.com"
            varsFile=~/.${NAME}.vars
            docker pull ${DOCKER_IMAGE}
            docker stop ${NAME} && docker rm ${NAME} || true
            docker run \
                --name ${NAME} \
                --detach \
                --publish-all \
                --restart on-failure \
                --env NAME=${NAME} \
                --env VIRTUAL_HOST=${url} \
                --env LETSENCRYPT_HOST=${url} \
                --env-file ${varsFile} \
                ${DOCKER_IMAGE}
